name: WorldGenerationControl
main: net.pointysoftware.worldgenerationcontrol.WorldGenerationControl
version: 2.4
author: john@pointysoftware.net

permissions:
   worldgenerationcontrol.generate:
      description: |
         Allows user to queue generations. Implicitly grants worldgenerationcontrol.statusupdates.
      children:
         worldgenerationcontrol.statusupdates: true
   worldgenerationcontrol.statusupdates:
      description: |
         Allows user to see progress of generations when connected.

commands:
   generateregion:
      aliases: genregion
      description: Queue the generation of a square region of chunks.
      usage: |
            Usage: /<command> WorldName xStart zStart xEnd zEnd
   
   generatecircularregion:
       aliases: gencircle
       description: Queue the generation of a circular region of chunks.
       usage: |
            Usage: /<command> Radius [WorldName xCenter zCenter]

   cancelgeneration:
      aliases: cancelgen
      description: Cancel all pending chunk generation.
